name: Update README Image

on:
  schedule:
    - cron: '0 0 * * MON'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Update README Image
      run: python .github/update.py README.md https://old-url.com/old-image.png https://www.coverbrowser.com/covers/weird-tales

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update image in README.md'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
